### ISSUE TITLE
Quilt Version 1.0.1 does not work on 1.19.2 or earlier

### ISSUE THREAD

**Issue by MarioAndWeegee3** [MrLoLf/InfinityFix#3]
Relevant part of log:

```
[13:29:48] [main/ERROR]: Incompatible mod set!
org.quiltmc.loader.impl.FormattedException: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'Infinity Fix' (infinityfix) v1.19.x-1.0.1+1.19.3:
Dependency for mod 'infinityfix' on quilted_fabric_api versions [>=5.0.0-] (0 valid options, 1 invalid options)
	x mod 'quilted_fabric_api' version 4.0.0-beta.26+0.72.0-1.19.2 loaded from mods/qfapi-4.0.0-beta.26_qsl-3.0.0-beta.25_fapi-0.72.0_mc-1.19.2.jar
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:214) ~[quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141) ~[quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.8.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'Infinity Fix' (infinityfix) v1.19.x-1.0.1+1.19.3:
Dependency for mod 'infinityfix' on quilted_fabric_api versions [>=5.0.0-] (0 valid options, 1 invalid options)
	x mod 'quilted_fabric_api' version 4.0.0-beta.26+0.72.0-1.19.2 loaded from mods/qfapi-4.0.0-beta.26_qsl-3.0.0-beta.25_fapi-0.72.0_mc-1.19.2.jar
	at org.quiltmc.loader.impl.solver.ModSolver.fallbackErrorDescription(ModSolver.java:615) ~[quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.solver.ModSolver.findCompatibleSet(ModSolver.java:244) ~[quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:434) ~[quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.8.jar:?]
	... 6 more
```

QFAPI 5.0.0 is only available for 1.19.3; so the mod will not work on 1.19.2 or any prior version.

**Comment by MrLoLf** [comment]
It should work now, thanks for pointing this out!
