### ISSUE TITLE
Invalid icon error in log

### ISSUE THREAD

**Issue by manuelgrabowski** [MrLoLf/InfinityFix#4]
Hey there, thanks for making this awesome mod! It works perfectly fine, I did notice this in my log however:

```
[00:45:28] [Render thread/ERROR]: Invalid mod icon for icon source infinityfix: assets/infinityandmending/icon.png
java.nio.file.NoSuchFileException: /assets/infinityandmending/icon.png
	at org.quiltmc.loader.impl.filesystem.QuiltZipFileSystemProvider.newInputStream(QuiltZipFileSystemProvider.java:130) ~[quilt-loader-0.18.3.jar:?]
	at java.nio.file.Files.newInputStream(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler.createIcon(FabricIconHandler.java:34) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:159) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:95) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:53) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:234) ~[transformed-mod-modmenu.i0:0/:?]
	at net.minecraft.class_350.method_25394(class_350.java:232) ~[transformed-mod-minecraft.i0:0/:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:275) ~[transformed-mod-modmenu.i0:0/:?]
	at net.minecraft.class_437.method_47413(class_437.java:113) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:929) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) ~[quilt-loader-0.18.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.18.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.18.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[00:45:28] [Render thread/WARN]: Warning! Mod infinityfix has a broken icon, loading default icon
```

Looks like it is referring to `infinityandmending` instead of `infinityfix` somewhere, because the file `assets/infinityfix/icon.png` does exist in the jar. :)

**Comment by MrLoLf** [comment]
Yeah, I've spotted the bug. I haven't changed the path, as I have copied stuff from another mod I've made. xD 
That's why it's mentioning `infinity and mending` and is searching there for an icon. I'll fix it and will update it today.

Thanks for the report ^^
